steps:
  # 1. Build the container image using Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hmc-volunteer-portal:$COMMIT_SHA', '.']

  # 2. Push the container image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hmc-volunteer-portal:$COMMIT_SHA']

  # 3. Deploy the new container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'hmc-volunteer-portal'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hmc-volunteer-portal:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--cpu=2'
      - '--memory=1Gi'
      - '--min-instances=1'
      - '--concurrency=50'
      - '--update-env-vars'
      - 'EMAIL_SERVICE_URL=https://script.google.com/macros/s/AKfycbxMOK7JiV_nTZKLQCDumFALNY_v-m-M5PST2zuhQLShT3WcqG_8hmTCcB6PHzHpcts4Tg/exec,APPS_SCRIPT_URL=https://script.google.com/macros/s/AKfycbyiCw_yisTVlgT5CGR07ABLNt0O-zEoHV7o6L3vLRTEaQJcDGXD00jkTinDVuZ_v_lBqA/exec,GOOGLE_CLIENT_ID=172668994130-a8po02ouqnfuab01ma6tfo7rh1c6c35f.apps.googleusercontent.com,VITE_GOOGLE_CLIENT_ID=172668994130-a8po02ouqnfuab01ma6tfo7rh1c6c35f.apps.googleusercontent.com'

images:
  - 'gcr.io/$PROJECT_ID/hmc-volunteer-portal:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
