// Static module content for governance and clinical read_ack training modules.
// Content sourced from HMC governance guide, board orientation speaker notes,
// and clinical standard operating procedures.

export type ModuleContent = { content: string; sections: { heading: string; body: string }[] };

export const STATIC_MODULE_CONTENT: Record<string, ModuleContent> = {
  // ==================== GOVERNANCE DOCUMENTS ====================
  'gov_coi_policy': {
    content: 'Official Conflict of Interest Policy for Health Matters Clinic. Adopted October 18, 2025. All directors, officers, key employees, and advisory members must read, understand, and comply with this policy.',
    sections: [
      { heading: '1. Purpose', body: 'The purpose of this Conflict of Interest Policy (the "Policy") is to protect the interests of Health Matters Clinic ("HMC") when it is contemplating a transaction or arrangement that might benefit the private interest of a director, officer, key employee, or advisory member ("Covered Person"). This policy ensures that all decisions are made in the best interest of the organization and the communities we serve.' },
      { heading: '2. Definitions', body: 'A Conflict of Interest exists when a Covered Person\'s personal, professional, or financial interests could reasonably be perceived to interfere with the best interests of HMC. A Related Party Transaction is any transaction between HMC and a Covered Person or a Family Member or entity in which such person has a Material Financial Interest.\n\nReal-world examples of conflicts at HMC include: having a financial interest in a vendor HMC is considering; serving on another board competing for the same grant; HMC considering hiring your firm for services; or your employer becoming a potential HMC partner. When in doubt, disclose. Disclosure protects both you and the organization.' },
      { heading: '3. Duty to Disclose', body: 'Covered Persons shall disclose in writing all actual or potential conflicts to the Board (or Governance Committee) promptly and no later than annually via the Disclosure Form. Disclosures shall be updated as circumstances change, including when you get a new job, start a business, or join another board.' },
      { heading: '4. Recusal & Determination', body: 'Any Covered Person with a potential conflict shall leave the meeting during discussion and voting on the matter. The disinterested directors shall determine whether a conflict exists and, if so, whether the proposed transaction is fair, reasonable, and in HMC\'s best interests after considering alternatives.' },
      { heading: '5. Documentation', body: 'Minutes shall reflect disclosures, recusals, deliberations, alternatives considered, and the vote. This documentation is essential for transparency and legal compliance.' },
      { heading: '6. Violations', body: 'Failure to disclose may result in corrective action up to and including removal, consistent with bylaws and applicable law. Undisclosed conflicts are what create legal and organizational risk — the act of disclosure itself is protective.' },
      { heading: '7. Annual Acknowledgment', body: 'All Covered Persons shall sign an annual acknowledgment affirming that they have received, read, and agree to comply with this Policy. The Annual Conflict of Interest Disclosure form must be completed annually and submitted to the Governance Committee.' }
    ]
  },
  'gov_code_of_ethics': {
    content: 'Official Code of Ethics for Health Matters Clinic. Adopted October 18, 2025. This code governs the conduct of all directors, officers, staff, volunteers, and advisors.',
    sections: [
      { heading: '1. Values & Conduct', body: 'Directors, officers, staff, volunteers, and advisors shall conduct themselves with integrity, fairness, respect, and accountability, advancing HMC\'s mission and avoiding any conduct that undermines public trust. This includes acting with honesty in all dealings, treating colleagues and community members with dignity, and upholding the highest standards of professional behavior.' },
      { heading: '2. Confidentiality', body: 'Information obtained through service to HMC, including personal information of clients, donors, volunteers, and partners, shall be protected and used solely for legitimate organizational purposes. What is discussed in Board meetings stays there, especially anything about clients, donors, or strategy. Breach of confidentiality may result in corrective action.' },
      { heading: '3. Conflicts, Gifts & Gratuities', body: 'Conflicts must be disclosed and managed per the Conflict of Interest Policy. Gifts or favors that could reasonably influence decision-making may not be solicited or accepted. When in doubt about whether something constitutes a conflict or improper gift, disclose it to the Governance Committee.' },
      { heading: '4. Use of Assets & Records', body: 'HMC resources shall be used responsibly and solely for organizational purposes. Records shall be accurate, timely, and retained per retention schedules and applicable law. This includes financial records, meeting minutes, program data, and all official correspondence.' },
      { heading: '5. Compliance & Reporting', body: 'Members shall comply with all applicable law and organizational policy. Good-faith concerns about violations may be reported without fear of retaliation. Retaliation for good-faith reporting is strictly prohibited. Reports may be directed to the Governance Committee, Executive Director, or Board Chair.' },
      { heading: '6. Enforcement', body: 'Violations of this Code of Ethics may result in corrective action up to and including removal, consistent with bylaws and due process. The goal is accountability, not punishment — we expect all members to uphold the trust placed in them by the communities we serve.' }
    ]
  },
  'gov_board_agreement': {
    content: 'Official Board Member Agreement for Health Matters Clinic. Effective for terms beginning on or after October 18, 2025. This agreement outlines your commitments as a director of HMC.',
    sections: [
      { heading: '1. Duties', body: 'As a director of HMC, I will discharge fiduciary duties of care, loyalty, and obedience; prepare for and attend meetings; serve on committees; and act in the best interests of HMC.\n\nDuty of Care means you cannot phone it in — read the materials, ask hard questions, and challenge assumptions. Duty of Loyalty means when there is a conflict between your interests and HMC\'s interests, HMC wins — always. Duty of Obedience means you are the guardian of the mission; if HMC ever drifts, you pull it back.' },
      { heading: '2. Participation', body: 'I will endeavor to attend at least 75% of board and committee meetings annually and be responsive to organizational communications. Board meetings are quarterly (first Monday of January, April, July, and October). Committee work is where detailed work happens — most Board members serve on 1-2 committees. The average time commitment is 3-5 hours per month.' },
      { heading: '3. Ethics & Conflicts', body: 'I will adhere to HMC\'s Code of Ethics and Conflict of Interest Policy, complete annual disclosures, and recuse when appropriate. This includes completing the Annual Conflict of Interest Disclosure form and updating it whenever circumstances change.' },
      { heading: '4. Confidentiality & Communications', body: 'I will maintain confidentiality of nonpublic information and direct media inquiries to authorized spokespersons. Board discussions, strategic plans, financial details, and information about clients, donors, and partners must remain confidential.' },
      { heading: '5. Support', body: 'I will act as an ambassador for HMC, assisting as able with strategic relationships and resource development. No mandatory give-get is imposed at this time. HMC values your expertise, connections, and advocacy. If you choose to give personally, that is welcome but never required. Your networks matter — being a champion for HMC\'s mission in your professional and personal circles is one of the most valuable contributions you can make.' },
      { heading: '6. Reimbursement', body: 'Reasonable, pre-approved expenses incurred on behalf of HMC will be reimbursed per policy. This includes travel to events, materials purchased for organizational purposes, and other expenses directly related to Board service.' },
      { heading: '7. Term & Separation', body: 'Terms are three (3) years unless otherwise stated. I may resign at any time by written notice; removal may occur per bylaws. Committee assignments can be rotated — they are not permanent.' },
      { heading: '8. Acknowledgment', body: 'By completing this module, I affirm my commitment to this Agreement and HMC policies. I understand that this agreement represents a genuine commitment to the organization and the communities it serves.' }
    ]
  },
  'gov_roles_expectations': {
    content: 'Roles and expectations for all HMC governance members, including fiduciary duties, time commitments, participation standards, and ambassadorial responsibilities.',
    sections: [
      { heading: 'Fiduciary Duties', body: 'All directors and advisors are expected to uphold three core fiduciary duties:\n\nDuty of Care: Prepare for and actively engage in meetings. Read materials in advance, ask hard questions, and challenge assumptions. Silence in the boardroom is not neutral — if you have doubts, voice them.\n\nDuty of Loyalty: Put HMC\'s interests above personal interests. When there is a conflict between your interests and HMC\'s interests, HMC wins. Always disclose potential conflicts.\n\nDuty of Obedience: Safeguard the mission and ensure the organization stays true to its purpose. You are the guardians of HMC\'s mission of breaking down barriers to health.' },
      { heading: 'Time & Participation', body: 'Quarterly full-board or CAB meetings are held on a set schedule, with committees convening monthly or as needed. You are expected to:\n\nPrepare by reviewing agendas, financials, minutes, and materials in advance — these arrive at least 7 days before meetings. Target 75% or higher attendance at scheduled meetings and notify the Board Chair of anticipated absences. Engage actively in discussions and committee work.' },
      { heading: 'Ambassadorial Duties', body: 'As a governance member, you champion HMC\'s mission and programs across your networks. You assist, as able, with fundraising, partnerships, and strategic visibility. You do not have to be a fundraiser, but you do need to be a champion. Your networks, expertise, and advocacy are among the most valuable resources you bring to HMC.' },
      { heading: 'Confidentiality & Ethics', body: 'Maintain confidentiality of all nonpublic information. Avoid and disclose conflicts of interest promptly. Conduct yourself in a manner that advances HMC\'s mission and reputation. Direct media inquiries to authorized spokespersons.' }
    ]
  },
  'gov_cab_scope': {
    content: 'Community Advisory Board (CAB) composition, terms, scope of advisory role, and responsibilities at Health Matters Clinic.',
    sections: [
      { heading: 'What is the CAB?', body: 'The Community Advisory Board (CAB) is an advisory body that provides lived-experience and sector expertise to inform programs, policy positions, community engagement, and quality improvement at Health Matters Clinic. CAB recommendations are non-binding but shall be recorded and considered by the Board and management. The CAB brings community voice directly into organizational decision-making.' },
      { heading: 'Composition & Terms', body: 'The CAB has diverse representation across the communities HMC serves. Appointments are made by the Board or its designee, with an emphasis on reflecting the populations and neighborhoods served by HMC programs. The standard term is two (2) years, renewable based on mutual agreement and continued engagement.' },
      { heading: 'Scope & Responsibilities', body: 'CAB members contribute in several key areas:\n\nProgram Feedback: Providing input on how HMC programs serve community needs and where improvements are needed.\n\nCommunity Needs Assessment: Sharing knowledge of on-the-ground conditions, emerging health concerns, and gaps in service.\n\nOutreach Support: Helping connect HMC with community members, organizations, and cultural networks.\n\nPolicy Education & Stakeholder Engagement: Informing policy positions and representing community perspectives.\n\nAd Hoc Working Groups: Participating in time-limited groups aligned to strategic initiatives as needed.' },
      { heading: 'Time Commitment & Meetings', body: 'CAB members average 2-3 hours per month. Quarterly CAB meetings are held on the third Monday of March, June, September, and December. Meetings are hybrid (in-person and virtual). Agendas and materials are distributed at least 7 days in advance. Committee work or special projects may add time seasonally.' }
    ]
  },
  'gov_bod_structure': {
    content: 'Board of Directors composition, term structure, and seven standing committees at Health Matters Clinic.',
    sections: [
      { heading: 'Board Composition & Terms', body: 'The Board of Directors is HMC\'s governing body. It is responsible for strategic direction; oversight of financial and operational integrity; selection, support, and evaluation of the chief executive; and safeguarding of mission and assets. Officers and directors serve as defined in the bylaws. The standard term is three (3) years, typically renewable once consecutively.' },
      { heading: 'Seven Standing Committees', body: 'The Board operates through seven standing committees where detailed governance work happens between quarterly meetings:\n\nExecutive Committee: Officers plus urgent items between meetings.\n\nGovernance & Nominations: Board recruitment, policies, succession planning.\n\nFinance, Audit & Risk: Budget oversight, audit management, risk assessment — critical oversight function.\n\nPrograms, Quality & Clinical Oversight: Service quality, clinical standards, and outcomes measurement.\n\nWorkforce Development & Education: Volunteer management, training programs, and organizational culture.\n\nDevelopment & Community Partnerships: Fundraising strategy, donor relations, and strategic partnerships.\n\nCommunity Engagement & Advocacy: Community outreach, policy positions, and public voice.' },
      { heading: 'Committee Assignments', body: 'Most Board members serve on 1-2 committees. Committee assignments are based on your expertise, interests, and organizational needs. Assignments are proposed after you complete your application. You can rotate committees — this is not permanent. Committee charters are adopted and may be amended by the Board.' },
      { heading: 'Governance & CAB Relationship', body: 'The Board governs; the Community Advisory Board advises. Both are essential. The CAB brings community voice directly into decision-making. CAB recommendations are not binding, but they should carry weight. Listen to them — their lived experience and community knowledge inform better decisions.' }
    ]
  },
  'gov_meetings_schedule': {
    content: 'Board and CAB meeting schedules, notice requirements, standard agenda, and what to expect at Health Matters Clinic governance meetings.',
    sections: [
      { heading: 'Meeting Schedule', body: 'Board of Directors: Quarterly meetings on the first Monday of January, April, July, and October. Meetings are typically 2 hours, with hybrid participation supported (in-person and Zoom).\n\nCommunity Advisory Board: Quarterly meetings on the third Monday of March, June, September, and December.\n\nCommittee Meetings: Monthly or as needed, depending on the committee and current organizational priorities.' },
      { heading: 'Notice & Preparation', body: 'Agendas and materials are distributed at least seven (7) days in advance of all meetings. This is your cue to block time and review. Materials typically include the agenda, prior meeting minutes, financial reports, program updates, and any items requiring Board action. Come prepared — preparation is a core part of your Duty of Care.' },
      { heading: 'Standard Meeting Agenda', body: 'Board meetings follow a standard agenda:\n\n1. Call to Order and Quorum Check (formal but quick)\n2. Approval of Agenda and Prior Minutes (5 minutes)\n3. Executive and Program Reports (30-40 minutes)\n4. Financial Report and Audit/Compliance Updates (20-30 minutes)\n5. Governance and Nominations (10 minutes)\n6. Strategic Items and New Business (20-30 minutes — this is where substantive debate happens)\n7. Public Comment, as applicable (5-10 minutes)\n8. Adjournment' },
      { heading: 'Meeting Expectations', body: 'Attendance target is 75% of scheduled meetings. Track this — if life happens, let the Board Chair know in advance. Hybrid participation is fully supported; meeting notices include connection details. Full materials arrive 7 days in advance. Engage actively — silence is not neutral. If you have questions or concerns, raise them.' }
    ]
  },
  'gov_coi_disclosure': {
    content: 'Annual Conflict of Interest Disclosure requirements for Health Matters Clinic governance members. Must be completed annually and upon any changes in circumstances.',
    sections: [
      { heading: 'Purpose', body: 'The Annual Conflict of Interest Disclosure form is required of all directors, officers, key employees, and advisory members. It ensures transparency and protects both you and the organization. This disclosure must be completed annually and submitted to the Governance Committee.' },
      { heading: 'What You Must Disclose', body: 'The disclosure form covers four areas:\n\n1. List any entities in which you or a Family Member hold a Material Financial Interest that may interact with HMC.\n\n2. List any positions (officer, director, employee, consultant) you hold with entities that may interact with HMC.\n\n3. Disclose any transactions with HMC in the past 12 months or anticipated in the next 12 months.\n\n4. Affirm you have read and agree to comply with the Conflict of Interest Policy.' },
      { heading: 'When to Update', body: 'Submit the disclosure form annually (due by January 31st) and whenever circumstances change. Common triggers for updates include: starting a new job, launching a business, joining another nonprofit board, a family member starting a business that could interact with HMC, or becoming aware of any new potential conflict. When in doubt, disclose — the act of disclosure is itself protective.' },
      { heading: 'Submission & Review', body: 'Submit completed forms to the Governance Committee. The Committee reviews all disclosures and determines whether any potential conflicts require management, recusal, or other action. All disclosures are kept confidential and reviewed in accordance with the Conflict of Interest Policy.' }
    ]
  },
  // ==================== CLINICAL DOCUMENTS ====================
  'credential_verification': {
    content: 'Credential verification and scope of practice requirements for licensed clinical volunteers at Health Matters Clinic. All licensed providers must complete this process before participating in clinical activities.',
    sections: [
      { heading: 'Who Must Complete Credentialing', body: 'All licensed clinical providers volunteering with HMC must complete credentialing before participating in any clinical activities. This includes Physician Associates (PAs), Physicians (MD/DO), Registered Nurses (RNs), Licensed Vocational Nurses (LVNs), Emergency Medical Technicians (EMTs), and Medical Assistants (MAs). Each role has specific documentation requirements based on licensure type and scope of practice under California law.' },
      { heading: 'Required Documentation', body: 'You must provide current, verifiable documentation of your professional license or certification issued by the State of California. This includes your license number, expiration date, and any specialty certifications. HMC verifies all credentials through the appropriate licensing board before granting clinical privileges. You are responsible for maintaining current credentials and notifying HMC immediately of any changes to your licensure status, restrictions, or disciplinary actions.' },
      { heading: 'Role-Based Scope at HMC', body: 'HMC is not a traditional brick-and-mortar clinic. We operate through mobile health teams, pop-up community clinics, street medicine outreach, and health fairs. Your scope of practice at HMC events is defined by both your professional license and HMC\'s clinical protocols.\n\nPhysician Associate (PA) — Clinical Lead: Develops and approves standing orders, performs all screenings independently, provides clinical oversight to all team members, and makes final decisions on abnormal results and referrals.\n\nMD/DO — Consulting Partner: Provides higher-level medical review, supports case escalation, and collaborates on clinical protocol development.\n\nRN: Performs screenings under approved standing orders, administers approved tests, provides health education, and supervises LVNs, MAs, and non-licensed volunteers. Complex assessments require PA consultation. Cannot diagnose or prescribe at HMC events.\n\nLVN/EMT/MA: Performs specific clinical tasks under direct supervision of RN or PA as defined by standing orders.' },
      { heading: 'Liability & Insurance', body: 'HMC maintains General Liability Insurance, Professional Liability Insurance, and Workers\' Compensation covering all team members including volunteers. Coverage applies when you are acting within your defined scope during official HMC events, following approved protocols and standing orders, under appropriate supervision, and documenting properly. Coverage may NOT apply when acting outside scope or without authorization, at non-HMC events, or in cases of gross negligence. HMC strongly recommends all licensed clinical providers maintain personal professional liability insurance as an additional layer of protection.' }
    ]
  },
  'clinical_sops': {
    content: 'HMC Clinical Standard Operating Procedures including standing orders, screening protocols, informed consent requirements, and documentation standards for community health events.',
    sections: [
      { heading: 'Standing Orders & Clinical Protocols', body: 'Standing orders are written medical protocols authorized by the Supervising Practitioner (PA) that allow certain screenings to be carried out by licensed staff or trained personnel within clear limits. All clinical activities at HMC events must be performed under an approved standing order.\n\nHMC focuses on prevention, early detection, stabilizing support, and navigation — NOT long-term diagnosis or ongoing treatment at the event itself. Services are offered regardless of insurance status, immigration status, gender identity, housing status, or ability to pay.' },
      { heading: 'Blood Pressure Screening Protocol', body: 'Who Can Perform: PA, RN, LVN, EMT independently. MA under RN/PA supervision. Trained CHW/volunteer under licensed supervision.\n\nNormal Range: Systolic below 120 mmHg AND Diastolic below 80 mmHg.\n\nImmediate PA Notification Required: Systolic 180 or above OR Diastolic 120 or above (hypertensive crisis), or Systolic 160 or above with symptoms.\n\nAdditional standing orders for blood glucose screening, HIV/STI testing, mental health screening, BMI assessment, and SDOH screening follow the same format with role-specific requirements and escalation protocols.' },
      { heading: 'Informed Consent Requirements', body: 'All participants must provide informed consent before receiving any screening or service. The consent process must communicate:\n\nThese are screenings, not diagnoses. Results are preliminary and require follow-up with a medical provider.\n\nParticipation is voluntary. Participants can decline any service or stop at any time.\n\nInformation is confidential. HMC protects participant privacy.\n\nParticipant rights include: the right to ask questions about any screening, the right to decline any or all services, the right to receive their results, and the right to referrals for follow-up care.\n\nStandardized language for community members: "Today\'s screening gives us a snapshot of your health. If we find anything that needs attention, we\'ll help you get connected to a doctor or clinic for follow-up."' },
      { heading: 'Documentation & Privacy', body: 'HMC currently collects de-identified or limited data in systems designed for program evaluation. No specific Protected Health Information (PHI) is stored digitally. Paper consent forms are stored securely with a focus on population-level insights.\n\nPrivacy protocols include: speaking quietly when discussing results, never disclosing results publicly, using private spaces for sensitive conversations, secure storage of all paper forms, and password-protected digital systems.\n\nAll care is delivered using a trauma-informed, culturally responsive, equity-focused approach. Use person-first language. Create judgment-free spaces. Co-create health solutions WITH communities, not FOR them.' }
    ]
  },
  'scope_of_practice': {
    content: 'Scope of Practice acknowledgment for clinical program volunteers at Health Matters Clinic. Understanding the boundaries between screenings and diagnosis under California law.',
    sections: [
      { heading: 'What HMC Provides vs. Does Not Provide', body: 'HMC provides screenings (preliminary tests identifying potential health risks), risk assessments (questionnaires identifying health concerns), health education (information about prevention and wellness), and navigation and referrals (connections to medical providers and resources).\n\nHMC does NOT provide onsite: definitive diagnosis (we identify concerns, not final diagnoses), medication prescribing, long-term treatment (we stabilize and refer, not manage ongoing care), or emergency medical services (critical emergencies require 911).' },
      { heading: 'California Law: Screenings vs. Diagnosis', body: 'Many HMC screenings and education services do NOT require licensure and can be performed by trained CHWs, volunteers, and students under appropriate supervision. However, anything that constitutes diagnosis, prescribing, or treatment is RESERVED for licensed providers within their legal scope of practice under California law.\n\nKey principle: licensure defines what clinical activities you can perform independently. Training defines what activities you can assist with under supervision.' },
      { heading: 'Role-Based Permissions', body: 'Physician Associate (PA) as Clinical Lead: Can develop and approve standing orders, perform all screenings independently, provide oversight to all team members, and make final decisions on results.\n\nRN: Can perform screenings under approved standing orders and supervise others. Complex assessments require PA consultation. Cannot diagnose or prescribe at HMC events.\n\nCommunity Health Workers and Navigators: Can conduct SDOH assessments, provide health education, perform non-clinical screenings like BMI and questionnaires, and assist with resource linkage. Clinical tasks like blood pressure and blood tests require licensed supervision. Cannot perform clinical assessments independently.' },
      { heading: 'Your Responsibility', body: 'Know your scope. Never exceed it. When in doubt, escalate to the Supervising Practitioner (PA). All clinical questions, abnormal results, or participant concerns must be immediately escalated to the on-site PA. If the PA is not available, contact the backup licensed provider or follow the emergency protocol.' }
    ]
  },
  'emergency_protocols': {
    content: 'Emergency response procedures, escalation paths, triage system, and crisis management protocols for Health Matters Clinic clinical and community events.',
    sections: [
      { heading: 'Traffic-Light Triage System', body: 'HMC uses a three-tier triage system at all events:\n\nGREEN (Routine): Stable participant, no urgent concerns. Standard screening flow, routine health education, non-urgent follow-up referrals.\n\nYELLOW (Urgent): Abnormal findings that need attention. PA reviews same-day, priority referral provided, follow-up expected within days to weeks. Notify the PA for review, provide counseling, give a written referral, and offer navigation support.\n\nRED (Emergency): Life-threatening situation. Immediately notify the PA. PA assesses urgency and determines if 911 is needed. Stay with the participant — do not leave them unattended.' },
      { heading: 'When to Call 911 Immediately', body: 'Call 911 without delay for any of the following:\n\nChest pain or pressure\nDifficulty breathing\nStroke symptoms (remember FAST: Face drooping, Arm weakness, Speech difficulty, Time to call 911)\nLoss of consciousness\nSeizure\nActive suicidal ideation with intent\nSevere allergic reaction (anaphylaxis)\n\nWhile waiting for EMS: stay with the participant, keep them calm, clear the area, and have someone meet the ambulance to direct them to the location.' },
      { heading: 'Abnormal Results Escalation Protocol', body: 'When screening results are abnormal (YELLOW level):\n\n1. Immediately notify the on-site PA or designated licensed provider.\n2. The PA reviews results and provides clinical assessment.\n3. Provide the participant with clear, non-alarming communication: "Your results show a finding which may need follow-up. This does not mean you definitely have a condition, but it is important to see a medical provider for complete evaluation."\n4. Provide a written referral with specific next steps.\n5. Offer navigation support to help connect them with follow-up care.\n6. Document the encounter, results, referral, and any follow-up plan.' },
      { heading: 'Chain of Command for Clinical Emergencies', body: 'Level 1: Board of Directors / Executive Director (organizational authority)\nLevel 2: Supervising Practitioner (PA) — Clinical Lead on Record (primary clinical decision-maker)\nLevel 3: Consulting MD/DO (partnership and review as needed)\nLevel 4: Licensed Clinical Staff (RN, LVN, EMT, MA)\nLevel 5: Community Health Workers and Health Navigators\nLevel 6: Volunteers, Students, Interns, and Outreach Teams\n\nALL clinical questions must be escalated to the on-site Supervising Practitioner. If the PA is not available, contact the backup licensed provider or follow the emergency protocol. Never attempt to handle a clinical emergency alone if you are not licensed and trained to do so.' }
    ]
  },
  'lmp_scope_review': {
    content: 'Scope of Practice review for licensed medical professionals volunteering with Health Matters Clinic. Understanding practice boundaries, liability protections, and your role in community health settings.',
    sections: [
      { heading: 'HMC\'s Clinical Model', body: 'Health Matters Clinic is NOT a traditional brick-and-mortar clinic. We operate through mobile health teams, pop-up community clinics, street medicine outreach, and health fairs. Our focus is prevention, early detection, stabilizing support, and navigation — not long-term diagnosis or ongoing treatment at events.\n\nAs a licensed medical professional, your scope at HMC events is defined by both your professional license under California law AND HMC\'s clinical protocols and standing orders. You must operate within both boundaries at all times.' },
      { heading: 'Role-Based Scope of Practice', body: 'Physician Associate (PA) — Clinical Lead and Supervising Practitioner on Record: Develops and approves standing orders and clinical protocols, performs all screenings and assessments independently, provides clinical oversight and supervision to all team members, escalates complex cases to consulting MD/DO as needed, trains and supervises licensed and non-licensed staff, and makes final decisions on abnormal results and referrals.\n\nMD/DO — Consulting Partner: Provides higher-level medical review and consultation, supports case escalation for complex medical situations, collaborates on clinical protocol development, and assists with alignment to state medical standards.\n\nRegistered Nurse (RN): Performs screenings under approved standing orders, administers approved tests (blood glucose, BP, rapid HIV/STI tests), provides health education and counseling, and supervises LVNs, MAs, and non-licensed volunteers. Complex assessments require PA consultation. Cannot diagnose or prescribe medications at HMC events.' },
      { heading: 'Liability & Good Samaritan Protections', body: 'HMC maintains General Liability Insurance, Professional Liability Insurance, and Workers\' Compensation covering all team members. Coverage applies when acting within scope during official HMC events, following approved protocols, under appropriate supervision, and with proper documentation.\n\nCoverage may NOT apply when acting outside scope or without authorization, at non-HMC events, in cases of gross negligence or willful misconduct, or when failing to follow protocols.\n\nHMC strongly recommends all licensed clinical providers maintain personal professional liability insurance as an additional layer of protection. Good Samaritan protections under California law may provide additional coverage for emergency medical care rendered in good faith.' },
      { heading: 'Key Principle: Screenings vs. Diagnosis', body: 'At HMC events, you provide screenings and risk assessments — NOT definitive diagnoses. Many HMC services do not require licensure and can be performed by trained CHWs and volunteers under supervision. However, anything that constitutes diagnosis, prescribing, or treatment is reserved for licensed providers within their legal scope.\n\nWhen communicating with participants, use standardized language: "These are screenings, not a diagnosis. Today\'s screening gives us a snapshot of your health. If we find anything that needs attention, we will help you get connected to a doctor or clinic for follow-up."' }
    ]
  },
  'lmp_triage_protocols': {
    content: 'Community Triage and Escalation Protocols for licensed medical professionals at Health Matters Clinic events. Includes the traffic-light triage system, 911 criteria, and chain of command.',
    sections: [
      { heading: 'HMC Triage System', body: 'HMC uses a traffic-light triage system at all community events:\n\nGREEN (Routine): Participant is stable with no urgent concerns. Proceed with standard screening flow, provide routine health education, and offer non-urgent follow-up referrals as appropriate.\n\nYELLOW (Urgent): Abnormal findings detected. The Supervising Practitioner (PA) must review same-day. Provide a priority referral with specific next steps. Expected follow-up within days to weeks. Offer navigation support to help connect the participant with care.\n\nRED (Emergency): Life-threatening situation. Immediately notify the PA. The PA assesses urgency and determines whether 911 is needed. Stay with the participant at all times — do not leave them unattended. Follow emergency protocols.' },
      { heading: 'When to Call 911', body: 'Call 911 immediately and without hesitation for:\n\nChest pain or pressure\nDifficulty breathing or respiratory distress\nStroke symptoms (FAST: Face drooping, Arm weakness, Speech difficulty, Time to call 911)\nLoss of consciousness or unresponsiveness\nSeizure activity\nActive suicidal ideation with clear intent or plan\nSevere allergic reaction or anaphylaxis\nAny situation where the participant\'s life appears to be in immediate danger\n\nWhile waiting for EMS: remain calm, stay with the participant, clear the area of bystanders, designate someone to meet the ambulance and direct them to the exact location, and begin appropriate first aid if trained and within scope.' },
      { heading: 'Escalation Protocol for Abnormal Results', body: 'Step 1: Immediately notify the on-site Supervising Practitioner (PA) or designated licensed provider of the abnormal finding.\n\nStep 2: The PA reviews results, performs a focused assessment, and determines the appropriate level of response.\n\nStep 3: Communicate clearly with the participant using non-alarming language: "Your results show a finding which may need follow-up. This does not mean you definitely have a condition, but it is important to see a medical provider for a complete evaluation."\n\nStep 4: Provide a written referral with specific recommendations for follow-up care, including suggested providers or clinics if available.\n\nStep 5: Offer navigation support to help connect the participant with follow-up resources.\n\nStep 6: Document the encounter thoroughly — results, assessment, referral, communication with participant, and any follow-up plan.' },
      { heading: 'Chain of Command', body: 'The clinical chain of command at HMC events:\n\nLevel 1: Board of Directors / Executive Director (organizational authority)\nLevel 2: Supervising Practitioner (PA) — Clinical Lead on Record and primary clinical decision-maker at events\nLevel 3: Consulting MD/DO — Available for partnership and review as needed\nLevel 4: Licensed Clinical Staff (RN, LVN, EMT, MA)\nLevel 5: Community Health Workers and Health Navigators\nLevel 6: Volunteers, Students, Interns, and Outreach Teams\n\nAll clinical questions, abnormal results, or participant concerns must be escalated to the on-site Supervising Practitioner. Never attempt to manage a situation beyond your training and scope.' }
    ]
  },
  'medical_records_basics': {
    content: 'Medical records, documentation requirements, and privacy protocols for healthcare administration volunteers at Health Matters Clinic community health events.',
    sections: [
      { heading: 'HMC Documentation Model', body: 'Health Matters Clinic currently operates in a two-phase digital strategy. In the current phase, HMC collects de-identified or limited data in systems designed for program evaluation. No specific Protected Health Information (PHI) is stored digitally at this time. Paper consent forms and screening records are stored securely, with the focus on population-level insights rather than individual patient records.\n\nHMC is building toward a HIPAA-compliant community health platform that will support secure storage of PHI, care coordination and follow-up, CHW documentation for Medi-Cal reimbursement, and digital navigation tools.' },
      { heading: 'Documentation Requirements at Events', body: 'As a medical admin volunteer, you play a critical role in ensuring proper documentation at HMC events. Key requirements include:\n\nConsent Forms: Every participant must sign an informed consent form before receiving screenings or services. Forms must be complete, legible, and include the participant\'s signature and date.\n\nScreening Records: All screening results must be documented accurately and completely. Include the screening type, results, any abnormal findings, and actions taken.\n\nReferral Documentation: When participants are referred for follow-up care, document the referral including the reason, recommended provider or facility, and any instructions given to the participant.\n\nEncounter Logs: Maintain running logs of encounters, services provided, and supplies used for program reporting and quality improvement.' },
      { heading: 'Privacy & Confidentiality Protocols', body: 'Protecting participant privacy is a fundamental obligation at all HMC events. Required practices include:\n\nSpeak quietly when discussing results with participants — never in earshot of others.\nNever disclose results publicly or to anyone other than the participant and authorized clinical staff.\nUse private or semi-private spaces for sensitive conversations, especially for HIV/STI results and mental health screenings.\nSecure storage of all paper forms — never leave forms unattended or visible to unauthorized persons.\nPassword-protected access for any digital systems used at events.\nProper disposal of any documents containing participant information when no longer needed.' },
      { heading: 'Your Role as Medical Admin', body: 'As a medical admin at HMC events, you support the clinical team by managing intake and registration, organizing and securing documentation, tracking encounter counts and screening data, ensuring consent forms are complete before participants proceed to screening stations, and maintaining organized records for post-event reporting.\n\nAll care at HMC is delivered using a trauma-informed, culturally responsive approach. Use person-first language in all documentation. Create a welcoming, judgment-free environment at intake and registration stations. If you encounter a participant in distress or with a clinical concern, immediately notify the on-site Supervising Practitioner (PA) — do not attempt to provide clinical advice or guidance.' }
    ]
  },

  // ==================== GOVERNANCE ORGANIZATIONAL DOCUMENTS ====================

  'gov_bylaws': {
    content: 'Bylaws of Health Matters Clinic, Inc. — A California Nonprofit Public Benefit Corporation organized under Section 501(c)(3) of the Internal Revenue Code. These bylaws govern the organizational structure, governance procedures, and operational framework of Health Matters Clinic.',
    sections: [
      { heading: 'Article I — Name, Purpose & Offices', body: 'Section 1.1 — Name. The name of this corporation shall be Health Matters Clinic, Inc. (hereinafter "HMC" or "the Organization").\n\nSection 1.2 — Purpose. HMC is organized and operated exclusively for charitable purposes within the meaning of Section 501(c)(3) of the Internal Revenue Code. The specific purpose of HMC is to improve community health outcomes and reduce health disparities in underserved communities in the greater Los Angeles area through preventive health screenings, health education, community wellness programming, street medicine outreach, and clinical services.\n\nSection 1.3 — Principal Office. The principal office of HMC shall be located in Los Angeles County, California, at such place as the Board of Directors may designate from time to time.\n\nSection 1.4 — Fiscal Year. The fiscal year of HMC shall begin on January 1 and end on December 31 of each year.' },
      { heading: 'Article II — Board of Directors', body: 'Section 2.1 — General Powers. The business and affairs of HMC shall be managed by its Board of Directors (the "Board"). The Board shall have all powers necessary to carry out the purposes of the Organization.\n\nSection 2.2 — Composition & Size. The Board shall consist of no fewer than five (5) and no more than fifteen (15) directors, as determined by Board resolution. Directors shall reflect the diversity of the communities served by HMC.\n\nSection 2.3 — Qualifications. Directors must be at least 18 years of age, committed to the mission of HMC, and willing to fulfill the duties and expectations of Board service. No more than 49% of directors may be "interested persons" as defined by California Corporations Code § 5227.\n\nSection 2.4 — Term of Office. Directors shall serve three-year (3-year) terms. Directors may serve a maximum of two (2) consecutive terms. After a one-year absence, a former director may be re-elected.\n\nSection 2.5 — Election. Directors shall be elected by a majority vote of the existing Board at the annual meeting, upon recommendation of the Governance & Nominations Committee.\n\nSection 2.6 — Vacancies. Vacancies on the Board may be filled by a majority vote of the remaining directors. A director appointed to fill a vacancy shall serve for the remainder of the unexpired term.\n\nSection 2.7 — Removal. A director may be removed with or without cause by a two-thirds (2/3) vote of the Board at a duly noticed meeting.\n\nSection 2.8 — Resignation. A director may resign at any time by delivering written notice to the Board Chair or Secretary. Resignation is effective upon receipt unless a later date is specified.\n\nSection 2.9 — Compensation. Directors shall serve without compensation for their Board service. Reasonable expenses incurred in the performance of Board duties may be reimbursed upon approval of the Executive Director or Board Chair.' },
      { heading: 'Article III — Officers', body: 'Section 3.1 — Officers. The officers of the Corporation shall be a Chair, Vice-Chair, Secretary, and Treasurer. Officers shall be elected from among the directors by a majority vote of the Board.\n\nSection 3.2 — Chair. The Chair shall preside at all Board meetings, serve as the primary liaison between the Board and the Executive Director, and represent the Board to external stakeholders.\n\nSection 3.3 — Vice-Chair. The Vice-Chair shall perform the duties of the Chair in the Chair\'s absence and shall assume other duties as assigned by the Board or the Chair.\n\nSection 3.4 — Secretary. The Secretary shall ensure that accurate minutes of all Board and committee meetings are recorded and maintained, that required notices are properly given, and that corporate records are kept current.\n\nSection 3.5 — Treasurer. The Treasurer shall oversee financial management, ensure the Board receives regular financial reports, chair the Finance, Audit & Risk Committee, and oversee the annual audit or financial review.\n\nSection 3.6 — Term & Removal. Officers shall serve two-year (2-year) terms and may be re-elected. An officer may be removed by a two-thirds (2/3) vote of the Board at any duly noticed meeting.' },
      { heading: 'Article IV — Meetings', body: 'Section 4.1 — Regular Meetings. The Board shall hold regular quarterly meetings on the first Monday of January, April, July, and October. The annual meeting shall coincide with the January quarterly meeting.\n\nSection 4.2 — Special Meetings. Special meetings may be called by the Chair, by the Executive Director, or by written request of at least one-third (1/3) of the directors then in office.\n\nSection 4.3 — Notice. Written notice of all meetings shall be delivered to each director at least seven (7) days before the meeting date. Notice shall include the date, time, location, and agenda.\n\nSection 4.4 — Quorum. A majority of the directors then in office shall constitute a quorum for the transaction of business.\n\nSection 4.5 — Voting. Each director shall have one vote. Unless otherwise specified in these Bylaws, decisions shall be made by a majority vote of directors present at a meeting at which a quorum is present.\n\nSection 4.6 — Remote Participation. Directors may participate in meetings via telephone or video conference, provided all participants can hear each other. Such participation constitutes presence in person.\n\nSection 4.7 — Action Without Meeting. The Board may take action without a meeting if all directors consent in writing to the action. Written consents shall be filed with the minutes.\n\nSection 4.8 — Attendance. Directors are expected to attend at least 75% of scheduled Board meetings per year. Three (3) consecutive unexcused absences may result in review by the Governance & Nominations Committee.' },
      { heading: 'Article V — Committees', body: 'Section 5.1 — Standing Committees. The Board shall have the following standing committees:\n\na) Executive Committee — Composed of the officers of the Board and the Executive Director (ex-officio, non-voting). May act on behalf of the Board between meetings on urgent matters, subject to full Board ratification.\n\nb) Governance & Nominations Committee — Responsible for Board recruitment, orientation, evaluation, and succession planning.\n\nc) Finance, Audit & Risk Committee — Oversees financial reporting, annual audit, risk management, and fiscal policy compliance.\n\nd) Programs, Quality & Clinical Oversight Committee — Reviews program effectiveness, clinical quality, and patient safety.\n\ne) Workforce Development & Education Committee — Oversees volunteer training, professional development, and workforce strategy.\n\nf) Development & Community Partnerships Committee — Guides fundraising strategy, grant development, and community partnerships.\n\ng) Community Engagement & Advocacy Committee — Advances community engagement, health equity advocacy, and public awareness.\n\nSection 5.2 — Committee Authority. Committees may make recommendations to the Board but shall not have the authority of the Board to act, except as specifically delegated in writing.\n\nSection 5.3 — Ad Hoc Committees. The Board may create ad hoc committees as needed for specific projects or initiatives.' },
      { heading: 'Article VI — Community Advisory Board', body: 'Section 6.1 — Establishment. HMC shall maintain a Community Advisory Board (CAB) to ensure community voice and accountability in organizational decision-making.\n\nSection 6.2 — Composition. The CAB shall consist of five to twelve (5-12) members representing diverse community perspectives, including community residents, people with lived experience of health disparities, local organizational partners, and youth or young adult representatives.\n\nSection 6.3 — Term. CAB members shall serve two-year (2-year) terms, with a maximum of three (3) consecutive terms.\n\nSection 6.4 — Meetings. The CAB shall meet quarterly on the third Monday of March, June, September, and December.\n\nSection 6.5 — Advisory Role. The CAB provides recommendations and community perspective to the Board of Directors. The Board shall receive and formally respond to CAB recommendations at least once per year.\n\nSection 6.6 — Working Groups. The CAB may form working groups to focus on specific topics such as health equity, outreach strategy, or community needs assessment.' },
      { heading: 'Article VII — Executive Director', body: 'Section 7.1 — Appointment. The Board shall appoint an Executive Director who shall serve as the chief executive officer of HMC and shall be responsible for the day-to-day management of the Organization.\n\nSection 7.2 — Authority. The Executive Director shall have authority to hire and manage staff, implement Board policies, execute contracts within approved budgets, and represent HMC to external stakeholders.\n\nSection 7.3 — Board Relationship. The Executive Director shall serve as an ex-officio, non-voting member of the Board and all standing committees. The Executive Director reports directly to the Board of Directors.\n\nSection 7.4 — Evaluation. The Board shall conduct an annual performance evaluation of the Executive Director.' },
      { heading: 'Article VIII — Conflicts of Interest', body: 'Section 8.1 — Policy. HMC shall adopt and maintain a Conflict of Interest Policy applicable to all directors, officers, and key employees. The policy shall require annual disclosure of potential conflicts and recusal from decisions involving conflicts.\n\nSection 8.2 — Disclosure. All directors, officers, and key employees must complete an annual Conflict of Interest Disclosure form.\n\nSection 8.3 — Procedures. When a conflict of interest is identified, the conflicted individual must disclose the conflict, recuse themselves from discussion and voting on the matter, and leave the room during deliberation and vote.' },
      { heading: 'Article IX — Indemnification & Insurance', body: 'Section 9.1 — Indemnification. HMC shall indemnify its directors and officers to the fullest extent permitted by the California Nonprofit Corporation Law.\n\nSection 9.2 — Insurance. HMC shall maintain Directors and Officers (D&O) liability insurance in amounts determined by the Board to be appropriate for the size and scope of the Organization\'s activities.' },
      { heading: 'Article X — Amendment & Dissolution', body: 'Section 10.1 — Amendment. These Bylaws may be amended by a two-thirds (2/3) vote of the Board at any duly noticed meeting, provided that proposed amendments are distributed to all directors at least fourteen (14) days before the vote.\n\nSection 10.2 — Dissolution. Upon dissolution of HMC, all remaining assets shall be distributed to one or more organizations organized and operated exclusively for exempt purposes under Section 501(c)(3), or to a federal, state, or local government for a public purpose, consistent with the requirements of the California Nonprofit Corporation Law and Section 501(c)(3) of the Internal Revenue Code.' }
    ]
  },

  'gov_strategic_plan': {
    content: 'Health Matters Clinic Strategic Plan 2024-2027. This framework outlines HMC\'s three-year strategic direction, goals, and key performance indicators. Note: Specific KPIs, targets, and timelines are to be defined by the Board of Directors during the upcoming strategic planning session.',
    sections: [
      { heading: 'Mission & Vision', body: 'Mission: Health Matters Clinic exists to improve community health outcomes and reduce health disparities by providing accessible, culturally responsive health education, screenings, and wellness programs to underserved communities in greater Los Angeles.\n\nVision: A Los Angeles where every community has equitable access to preventive health resources, health literacy, and pathways to care — regardless of income, insurance status, or immigration status.' },
      { heading: 'Strategic Priority 1: Program Excellence & Expansion', body: 'Goal: Expand HMC\'s reach and impact through high-quality, evidence-based community health programs.\n\nObjectives:\n\u2022 Increase the number of community health events from [current baseline] to [target] by 2027\n\u2022 Expand Street Medicine outreach to [number] new service areas\n\u2022 Launch [number] new program partnerships with FQHCs and community clinics\n\u2022 Achieve [target]% participant satisfaction rating across all programs\n\nKey Performance Indicators (to be defined by Board):\n\u2022 Total participants served annually\n\u2022 Number of screenings performed\n\u2022 Referral completion rate\n\u2022 Participant follow-up rate at 30/60/90 days' },
      { heading: 'Strategic Priority 2: Clinical Quality & Compliance', body: 'Goal: Establish and maintain clinical excellence across all service delivery programs.\n\nObjectives:\n\u2022 Implement comprehensive clinical quality assurance program\n\u2022 Achieve and maintain compliance with all applicable regulations\n\u2022 Develop standardized clinical protocols for all service types\n\u2022 Build pathway toward HIPAA-compliant digital health records\n\nKey Performance Indicators (to be defined by Board):\n\u2022 Clinical protocol adherence rate\n\u2022 Incident/adverse event rate\n\u2022 Provider credentialing completion rate\n\u2022 Training compliance percentage' },
      { heading: 'Strategic Priority 3: Workforce Development', body: 'Goal: Build a skilled, diverse, and engaged volunteer workforce that reflects the communities we serve.\n\nObjectives:\n\u2022 Recruit and onboard [target] new volunteers annually\n\u2022 Achieve [target]% volunteer retention rate year-over-year\n\u2022 Launch CHW certification pathway for eligible volunteers\n\u2022 Develop leadership pipeline for program coordinators and team leads\n\nKey Performance Indicators (to be defined by Board):\n\u2022 Active volunteer count\n\u2022 Volunteer hours contributed\n\u2022 Training completion rate\n\u2022 Volunteer-to-leader promotion rate' },
      { heading: 'Strategic Priority 4: Financial Sustainability', body: 'Goal: Diversify revenue and build long-term financial sustainability.\n\nObjectives:\n\u2022 Diversify revenue across at least [number] funding sources\n\u2022 Develop earned revenue strategy (CHW billing, consulting, training fees)\n\u2022 Build operating reserve to [number] months of expenses\n\u2022 Secure multi-year grant commitments from [number] funders\n\nKey Performance Indicators (to be defined by Board):\n\u2022 Total annual revenue\n\u2022 Revenue diversification ratio\n\u2022 Grant success rate\n\u2022 Operating reserve months' },
      { heading: 'Strategic Priority 5: Governance & Infrastructure', body: 'Goal: Strengthen organizational governance, technology, and operational infrastructure to support growth.\n\nObjectives:\n\u2022 Achieve full Board composition of [target] members with diverse expertise\n\u2022 Implement integrated volunteer management and program tracking platform\n\u2022 Complete governance policy review and update cycle\n\u2022 Develop succession plans for key leadership positions\n\nKey Performance Indicators (to be defined by Board):\n\u2022 Board meeting attendance rate\n\u2022 Board diversity metrics\n\u2022 Policy compliance audit results\n\u2022 Technology system uptime and adoption' },
      { heading: 'Implementation Timeline', body: 'Year 1 (2024-2025) — Foundation:\n\u2022 Complete strategic plan KPI definition (Board responsibility)\n\u2022 Establish baseline measurements for all indicators\n\u2022 Launch volunteer portal and digital training platform\n\u2022 Conduct governance policy review\n\nYear 2 (2025-2026) — Growth:\n\u2022 Expand programs based on Year 1 data\n\u2022 Launch new partnerships and funding streams\n\u2022 Implement clinical quality assurance program\n\u2022 Begin CHW certification pathway development\n\nYear 3 (2026-2027) — Sustainability:\n\u2022 Evaluate strategic plan progress against targets\n\u2022 Develop next strategic plan cycle\n\u2022 Establish earned revenue programs\n\u2022 Complete digital health records implementation planning\n\nNote: The Board of Directors is responsible for approving specific targets, reviewing progress quarterly, and adjusting priorities as needed based on organizational capacity and community needs.' }
    ]
  },

  'gov_board_handbook': {
    content: 'Board Member Handbook for Health Matters Clinic. This comprehensive guide covers everything board members need to know about their roles, responsibilities, governance processes, and how to be an effective contributor to HMC\'s mission.',
    sections: [
      { heading: 'Welcome & Organization Overview', body: 'Welcome to the Health Matters Clinic Board of Directors. As a board member, you play a vital governance role in advancing health equity in Los Angeles. HMC is a 501(c)(3) nonprofit organization that provides community health screenings, health education, street medicine outreach, and clinical services to underserved populations.\n\nOur core programs include:\n\u2022 Community Health Outreach — Health fairs, screenings, and wellness events\n\u2022 Street Medicine — Mobile outreach to people experiencing homelessness\n\u2022 Clinical Services — Licensed provider-supervised screenings and assessments\n\u2022 Community Wellness — Health education, peer support, and prevention programming\n\nHMC operates primarily through a trained volunteer workforce, supported by a small staff team and supervised by licensed clinical professionals.' },
      { heading: 'Your Three Fiduciary Duties', body: 'As a nonprofit board member in California, you hold three core fiduciary duties:\n\n1. Duty of Care — Act with the care that an ordinarily prudent person in a similar position would exercise under similar circumstances. This means attending meetings, reading materials, asking informed questions, and participating actively in Board decisions. You don\'t need to be an expert in everything, but you must make a reasonable effort to be informed.\n\n2. Duty of Loyalty — Put HMC\'s interests above your own personal or professional interests. Disclose any potential conflicts of interest, recuse yourself from conflicted decisions, and never use your Board position for personal gain or to benefit affiliated organizations without full transparency and Board approval.\n\n3. Duty of Obedience — Ensure HMC operates in accordance with its mission, Articles of Incorporation, Bylaws, and all applicable laws and regulations. This includes ensuring charitable assets are used for their intended purpose and that the organization complies with federal, state, and local requirements.' },
      { heading: 'Time Commitment & Expectations', body: 'Board service at HMC requires approximately 3-5 hours per month, including:\n\n\u2022 Quarterly Board Meetings: First Monday of January, April, July, and October (5:30-7:30 PM PT). Board members are expected to attend at least 75% of scheduled meetings.\n\u2022 Committee Participation: Each board member serves on at least one standing committee. Committee meetings are typically monthly, 1 hour each.\n\u2022 Preparation: Review meeting materials, financial reports, and committee updates before each meeting (approximately 1-2 hours per quarter).\n\u2022 Ambassador Activities: Represent HMC at community events, make introductions, and advocate for the organization\'s mission as opportunities arise.\n\nImportant: HMC does not have a "give or get" financial requirement. We value your time, expertise, and connections. If you are able to make a personal gift or help with fundraising, that is appreciated but never required.' },
      { heading: 'Standing Committees', body: 'HMC has seven standing committees. Each board member serves on at least one:\n\n1. Executive Committee — Officers of the Board plus ED (ex-officio). Handles urgent matters between full Board meetings. Meets as needed.\n\n2. Governance & Nominations Committee — Recruits new board members, manages orientation and onboarding, conducts annual Board self-assessment, and maintains governance policies.\n\n3. Finance, Audit & Risk Committee — Reviews financial statements, oversees annual audit/review, monitors budget performance, and assesses organizational risks.\n\n4. Programs, Quality & Clinical Oversight Committee — Reviews program outcomes and quality metrics, oversees clinical safety protocols, and evaluates program effectiveness.\n\n5. Workforce Development & Education Committee — Oversees volunteer recruitment and training strategy, reviews professional development programs, and supports the volunteer pipeline.\n\n6. Development & Community Partnerships Committee — Guides fundraising strategy, supports grant development, cultivates donor relationships, and builds community partnerships.\n\n7. Community Engagement & Advocacy Committee — Advances community outreach strategy, supports health equity advocacy, and builds public awareness of HMC\'s mission.' },
      { heading: 'Meeting Preparation & Participation', body: 'To be an effective board member:\n\nBefore meetings:\n\u2022 Read the board packet materials in advance (agenda, minutes, financial reports, committee updates)\n\u2022 Prepare questions and comments\n\u2022 Flag any potential conflicts of interest related to agenda items\n\nDuring meetings:\n\u2022 Arrive on time and stay for the full meeting\n\u2022 Participate actively in discussion — your perspective matters\n\u2022 Ask questions when you don\'t understand something\n\u2022 Focus on governance and strategy, not operational details\n\u2022 Vote on all matters unless recused for a conflict of interest\n\nAfter meetings:\n\u2022 Follow through on any commitments you made\n\u2022 Share relevant opportunities or connections with staff\n\u2022 Maintain confidentiality of Board discussions\n\nThe standard Board meeting agenda follows this flow:\n1. Call to Order & Quorum\n2. Approval of Agenda & Prior Minutes\n3. Executive & Program Reports\n4. Financial Report & Audit/Compliance Updates\n5. Governance & Nominations\n6. Strategic Items / New Business\n7. Public Comment (as applicable)\n8. Adjournment' },
      { heading: 'Onboarding Checklist', body: 'New board members should complete the following within their first 90 days:\n\n\u25a1 Review and sign the Board Member Agreement\n\u25a1 Review and sign the Conflict of Interest Policy & Disclosure Form\n\u25a1 Review and sign the Code of Ethics\n\u25a1 Review and sign the Confidentiality Agreement\n\u25a1 Complete all governance training modules in the Volunteer Portal\n\u25a1 Attend orientation session with Board Chair and Executive Director\n\u25a1 Review the HMC Bylaws, Strategic Plan, and most recent financial statements\n\u25a1 Select committee assignment(s)\n\u25a1 Attend first committee meeting\n\u25a1 Meet key staff members and program leads\n\u25a1 Attend or observe at least one HMC community event\n\nAll training modules and governance documents are available through the HMC Volunteer Portal under your Role Training section.' },
      { heading: 'Key Policies & Resources', body: 'As a board member, you are bound by the following policies (all available as separate documents in your governance library):\n\n\u2022 Conflict of Interest Policy — Annual disclosure required; recusal from conflicted decisions\n\u2022 Code of Ethics — Standards of conduct, confidentiality, and compliance\n\u2022 Whistleblower Policy — Procedures for reporting concerns about fraud, waste, or misconduct\n\u2022 Financial Policies & Procedures — Fiscal controls, approval thresholds, and audit requirements\n\u2022 D&O Insurance — Directors and Officers liability coverage for your protection\n\nFor questions about your Board service, contact:\n\u2022 Board Chair — For governance and Board-related matters\n\u2022 Executive Director — For organizational and operational questions\n\u2022 Board Secretary — For meeting logistics, minutes, and records' }
    ]
  },

  'gov_financial_policies': {
    content: 'Financial Policies and Procedures for Health Matters Clinic. These policies establish the fiscal controls, approval processes, and financial management standards that govern HMC\'s financial operations.',
    sections: [
      { heading: 'Financial Oversight & Authority', body: 'The Board of Directors has ultimate fiduciary responsibility for HMC\'s financial health. The Finance, Audit & Risk Committee provides detailed financial oversight and reports to the full Board quarterly.\n\nApproval Authority Thresholds:\n\u2022 Up to $500 — Executive Director may approve independently\n\u2022 $501 - $2,500 — Executive Director with Board Treasurer notification\n\u2022 $2,501 - $10,000 — Executive Director plus Board Treasurer approval\n\u2022 $10,001 - $25,000 — Executive Committee approval required\n\u2022 Over $25,000 — Full Board approval required\n\nAll expenditures must be consistent with the approved annual budget. Expenditures outside the approved budget require Board approval regardless of amount.' },
      { heading: 'Budget Development & Monitoring', body: 'Annual Budget Process:\n\u2022 The Executive Director prepares a proposed annual budget with staff input\n\u2022 The Finance, Audit & Risk Committee reviews and recommends the budget to the Board\n\u2022 The full Board approves the annual budget at the January meeting (or prior to the start of the fiscal year)\n\u2022 Budget amendments exceeding 10% of any line item require Board approval\n\nFinancial Reporting:\n\u2022 Monthly financial statements prepared by the Executive Director or designated financial staff\n\u2022 Quarterly financial reports presented to the full Board, including budget-to-actual comparisons, cash flow analysis, and grant expenditure tracking\n\u2022 Year-end financial statements prepared within 60 days of fiscal year end' },
      { heading: 'Revenue & Grants Management', body: 'Revenue Recognition: All revenue shall be recorded in accordance with Generally Accepted Accounting Principles (GAAP) for nonprofit organizations.\n\nGrant Management:\n\u2022 Grant applications over $10,000 require Board notification; over $50,000 require Board approval\n\u2022 Restricted grant funds shall be tracked separately and used only for designated purposes\n\u2022 Grant reporting deadlines shall be tracked and reports submitted on time\n\u2022 The Executive Director is responsible for grant compliance; the Finance Committee provides oversight\n\nDonor Stewardship:\n\u2022 All donations shall be acknowledged with a written receipt within 48 hours\n\u2022 Donations of $250 or more shall include IRS-required substantiation language\n\u2022 Donor intent shall be respected for all restricted gifts\n\u2022 Anonymous donations shall be honored per donor request' },
      { heading: 'Internal Controls & Segregation of Duties', body: 'Cash & Banking:\n\u2022 All bank accounts require two authorized signatories for checks over $1,000\n\u2022 Bank statements shall be reviewed monthly by someone other than the check signer\n\u2022 Petty cash shall not exceed $200 and must be reconciled monthly\n\u2022 All receipts must be retained for expenditures\n\nSegregation of Duties:\n\u2022 No single individual shall have control over all aspects of any financial transaction\n\u2022 The person who authorizes a payment should not be the same person who processes it\n\u2022 Bank reconciliations shall be performed by someone other than the person who records transactions\n\nCredit Card Policy:\n\u2022 Organizational credit cards may be issued with Board Treasurer approval\n\u2022 Monthly credit card statements must be reviewed and approved by the Executive Director\n\u2022 Personal charges on organizational cards are strictly prohibited\n\u2022 All credit card purchases require itemized receipts' },
      { heading: 'Audit & Compliance', body: 'Annual Audit:\n\u2022 HMC shall engage an independent Certified Public Accountant (CPA) to conduct an annual audit or financial review, depending on organizational size and funder requirements\n\u2022 The Finance, Audit & Risk Committee shall select the auditor (rotating every 3-5 years)\n\u2022 The auditor shall present findings directly to the Finance Committee and Board\n\u2022 Management response to audit findings shall be prepared within 30 days\n\nTax Compliance:\n\u2022 IRS Form 990 shall be prepared annually and reviewed by the Finance Committee before filing\n\u2022 Form 990 shall be made available to the public as required by law\n\u2022 California state filings (Form 199, RRF-1) shall be filed on time\n\u2022 All payroll taxes shall be deposited on schedule\n\nDocument Retention:\n\u2022 Financial records: 7 years\n\u2022 Tax returns and audit reports: Permanent\n\u2022 Grant records: 7 years after grant close-out\n\u2022 Bank statements: 7 years' },
      { heading: 'Expense Reimbursement', body: 'Board members and volunteers may be reimbursed for reasonable expenses incurred in the performance of their HMC duties.\n\nReimbursable Expenses:\n\u2022 Mileage for HMC-related travel at the current IRS standard rate\n\u2022 Parking and tolls for HMC events and meetings\n\u2022 Supplies purchased for HMC programs with prior approval\n\u2022 Registration fees for HMC-approved training or conferences\n\nReimbursement Process:\n\u2022 Submit expense report with itemized receipts within 30 days\n\u2022 Expense reports require supervisor or Board Chair approval\n\u2022 Reimbursements are processed within 15 business days\n\u2022 Expenses without receipts will not be reimbursed\n\nNon-Reimbursable Expenses:\n\u2022 Alcohol\n\u2022 Personal entertainment\n\u2022 Clothing (unless required safety equipment)\n\u2022 Fines, penalties, or late fees' }
    ]
  },

  'gov_whistleblower': {
    content: 'Whistleblower Policy for Health Matters Clinic. This policy establishes procedures for reporting suspected fraud, waste, abuse, or misconduct, and protections for individuals who report in good faith.',
    sections: [
      { heading: 'Purpose & Scope', body: 'Health Matters Clinic is committed to operating with the highest standards of ethical conduct, transparency, and accountability. This Whistleblower Policy provides a mechanism for directors, officers, employees, volunteers, and other stakeholders to report concerns about suspected fraud, waste, abuse, or other misconduct without fear of retaliation.\n\nThis policy applies to all directors, officers, employees, volunteers, consultants, and contractors of HMC. It covers concerns related to:\n\u2022 Financial fraud, theft, or embezzlement\n\u2022 Misuse of organizational funds or assets\n\u2022 Violations of laws, regulations, or HMC policies\n\u2022 Conflicts of interest that have not been properly disclosed\n\u2022 Threats to health, safety, or the environment\n\u2022 Retaliation against individuals who report concerns\n\u2022 Any other conduct that undermines public trust in HMC' },
      { heading: 'Reporting Procedures', body: 'Individuals who become aware of suspected misconduct are encouraged to report their concerns through any of the following channels:\n\n1. Direct Report: Notify your supervisor, the Executive Director, or the Board Chair\n2. Governance Committee: Contact the Chair of the Governance & Nominations Committee directly\n3. Written Report: Submit a written report (may be anonymous) to the Board Chair or Governance Committee Chair\n\nReports should include as much specific information as possible, including:\n\u2022 Description of the suspected misconduct\n\u2022 Names of individuals involved\n\u2022 Dates, locations, and other relevant details\n\u2022 Any documents or evidence supporting the concern\n\u2022 Whether the concern has been previously reported\n\nAnonymous reports will be accepted and investigated to the extent possible, though providing contact information may facilitate a more thorough investigation.' },
      { heading: 'Investigation Process', body: 'Upon receiving a report, the following process will be followed:\n\n1. Initial Review: The Board Chair or Governance Committee Chair will conduct an initial review within five (5) business days to determine if the report warrants a formal investigation.\n\n2. Investigation: If warranted, an investigation will be conducted by the Governance & Nominations Committee or an independent party designated by the Committee. The investigation will be conducted promptly, thoroughly, and confidentially.\n\n3. Findings: Investigation findings will be documented in writing and reported to the Board of Directors (or a subset of the Board if certain members are subjects of the investigation).\n\n4. Action: The Board will determine appropriate corrective action based on investigation findings, which may include policy changes, personnel action, referral to law enforcement, or other remedial measures.\n\n5. Closure: The reporting individual will be notified of the investigation\'s conclusion to the extent permitted by confidentiality and legal requirements.\n\nIf the report involves the Executive Director, the investigation will be handled directly by the Board Chair and Governance Committee. If the report involves the Board Chair, the Vice-Chair and Governance Committee will handle the investigation.' },
      { heading: 'Protection Against Retaliation', body: 'HMC strictly prohibits retaliation against any individual who makes a good-faith report of suspected misconduct under this policy. Retaliation includes, but is not limited to:\n\n\u2022 Termination, demotion, or suspension\n\u2022 Harassment, intimidation, or threats\n\u2022 Reduction in duties, hours, or responsibilities\n\u2022 Exclusion from meetings, events, or opportunities\n\u2022 Any other adverse action taken because of the report\n\nAny individual who retaliates against a whistleblower will be subject to disciplinary action, up to and including removal from the Board, termination of employment, or termination of volunteer status.\n\nProtection under this policy requires that the report be made in good faith — meaning the individual has a reasonable belief that the information provided is true. Reports made with malicious intent or with knowledge that the allegations are false are not protected and may themselves be subject to disciplinary action.' },
      { heading: 'Confidentiality', body: 'HMC will make every reasonable effort to maintain the confidentiality of the reporting individual\'s identity, consistent with the need to conduct a thorough investigation and comply with applicable law.\n\nInformation about reported concerns will be shared only on a need-to-know basis with individuals involved in the investigation or required by law.\n\nAll individuals involved in an investigation are expected to maintain strict confidentiality throughout the process.' },
      { heading: 'Board Responsibility & Annual Review', body: 'The Governance & Nominations Committee is responsible for overseeing the implementation of this policy and ensuring that all reports are handled appropriately.\n\nThis policy shall be:\n\u2022 Distributed to all directors, officers, employees, and volunteers during onboarding\n\u2022 Reviewed annually by the Governance & Nominations Committee\n\u2022 Available at all times through the HMC Volunteer Portal governance document library\n\nThe Board Chair shall report annually to the full Board on the number of reports received, investigations conducted, and actions taken (without identifying specific individuals), to ensure ongoing accountability and transparency.' }
    ]
  },

  'gov_committee_charters': {
    content: 'Standing Committee Charters for Health Matters Clinic Board of Directors. Each charter defines the committee\'s purpose, composition, responsibilities, and meeting expectations.',
    sections: [
      { heading: 'Executive Committee', body: 'Purpose: To act on behalf of the Board of Directors on urgent matters that arise between regular Board meetings, and to support the Board Chair in setting meeting agendas and priorities.\n\nComposition: Board Chair (serves as Committee Chair), Vice-Chair, Secretary, Treasurer, and the Executive Director (ex-officio, non-voting).\n\nResponsibilities:\n\u2022 Act on urgent matters between Board meetings, subject to full Board ratification at the next meeting\n\u2022 Set the agenda for Board meetings in consultation with the Executive Director\n\u2022 Oversee the annual performance evaluation of the Executive Director\n\u2022 Coordinate the work of all standing committees\n\u2022 Provide counsel and support to the Executive Director on organizational issues\n\nMeetings: As needed, typically monthly or at the call of the Chair.\n\nReporting: Actions taken between Board meetings shall be reported to the full Board at the next regular meeting.' },
      { heading: 'Governance & Nominations Committee', body: 'Purpose: To ensure effective Board governance through recruitment, orientation, evaluation, and policy oversight.\n\nComposition: At least three (3) Board members, including the Board Secretary.\n\nResponsibilities:\n\u2022 Identify, recruit, and vet prospective Board members with skills, experience, and diversity needed\n\u2022 Manage Board member orientation and onboarding\n\u2022 Conduct annual Board self-assessment\n\u2022 Maintain and update governance policies (Bylaws, Conflict of Interest, Code of Ethics, etc.)\n\u2022 Oversee Board member term tracking and succession planning\n\u2022 Manage the Whistleblower Policy and oversee investigations as needed\n\u2022 Recommend officer slate for annual elections\n\nMeetings: Monthly or as needed.\n\nReporting: Quarterly report to the full Board on governance activities, recruitment pipeline, and policy updates.' },
      { heading: 'Finance, Audit & Risk Committee', body: 'Purpose: To provide financial oversight, ensure fiscal responsibility, and manage organizational risk.\n\nComposition: At least three (3) Board members, including the Treasurer (who serves as Committee Chair). At least one member should have financial or accounting expertise.\n\nResponsibilities:\n\u2022 Review monthly financial statements and budget-to-actual reports\n\u2022 Recommend the annual budget to the Board for approval\n\u2022 Oversee the annual audit or financial review process\n\u2022 Select and engage the independent auditor (rotating every 3-5 years)\n\u2022 Review and update financial policies and procedures\n\u2022 Assess organizational risks and recommend risk mitigation strategies\n\u2022 Review insurance coverage annually\n\u2022 Ensure compliance with IRS, state, and funder financial reporting requirements\n\nMeetings: Monthly.\n\nReporting: Quarterly financial report to the full Board, including budget status, cash position, and any financial concerns.' },
      { heading: 'Programs, Quality & Clinical Oversight Committee', body: 'Purpose: To ensure HMC programs are effective, safe, and aligned with the organizational mission and community needs.\n\nComposition: At least three (3) Board members, preferably including members with healthcare, public health, or program management experience.\n\nResponsibilities:\n\u2022 Review program outcomes, quality metrics, and participant feedback\n\u2022 Oversee clinical safety protocols and incident reporting\n\u2022 Evaluate program effectiveness and recommend improvements\n\u2022 Review scope of practice compliance for clinical programs\n\u2022 Monitor credentialing and training compliance for clinical volunteers\n\u2022 Assess community health needs and recommend program priorities\n\u2022 Review and approve clinical standard operating procedures\n\nMeetings: Monthly or as needed.\n\nReporting: Quarterly report to the full Board on program metrics, quality indicators, and clinical safety.' },
      { heading: 'Workforce Development & Education Committee', body: 'Purpose: To oversee volunteer recruitment, training, professional development, and workforce strategy.\n\nComposition: At least three (3) Board members.\n\nResponsibilities:\n\u2022 Oversee volunteer recruitment and retention strategy\n\u2022 Review and approve training curriculum and modules\n\u2022 Monitor training completion rates and identify gaps\n\u2022 Support professional development opportunities for volunteers and staff\n\u2022 Guide the development of CHW certification pathways\n\u2022 Evaluate volunteer satisfaction and engagement\n\u2022 Recommend workforce policies and procedures\n\nMeetings: Monthly or as needed.\n\nReporting: Quarterly report to the full Board on volunteer metrics, training compliance, and workforce development initiatives.' },
      { heading: 'Development & Community Partnerships Committee', body: 'Purpose: To guide fundraising strategy, donor cultivation, grant development, and community partnerships.\n\nComposition: At least three (3) Board members, preferably including members with fundraising, grant writing, or community partnership experience.\n\nResponsibilities:\n\u2022 Develop and oversee the annual fundraising plan\n\u2022 Identify and cultivate prospective donors and partners\n\u2022 Support grant research, writing, and reporting\n\u2022 Build relationships with community organizations, healthcare providers, and government agencies\n\u2022 Plan and support fundraising events and campaigns\n\u2022 Track fundraising progress against goals\n\u2022 Ensure donor stewardship and recognition\n\nMeetings: Monthly or as needed.\n\nReporting: Quarterly report to the full Board on fundraising progress, grant pipeline, and partnership development.' },
      { heading: 'Community Engagement & Advocacy Committee', body: 'Purpose: To advance community engagement, health equity advocacy, and public awareness of HMC\'s mission.\n\nComposition: At least three (3) Board members. Community Advisory Board liaison recommended.\n\nResponsibilities:\n\u2022 Guide community outreach and engagement strategy\n\u2022 Advocate for health equity policies at local and state levels\n\u2022 Build public awareness of HMC\'s mission and programs\n\u2022 Support community health needs assessments\n\u2022 Coordinate with the Community Advisory Board on community priorities\n\u2022 Oversee social media, communications, and marketing strategy\n\u2022 Represent HMC at community forums and coalition meetings\n\nMeetings: Monthly or as needed.\n\nReporting: Quarterly report to the full Board on community engagement activities, advocacy efforts, and communications metrics.' }
    ]
  },

  'gov_dno_insurance': {
    content: 'Directors and Officers (D&O) Liability Insurance Summary for Health Matters Clinic. This document provides an overview of D&O coverage that protects board members and officers serving HMC.',
    sections: [
      { heading: 'What is D&O Insurance?', body: 'Directors and Officers (D&O) Liability Insurance provides financial protection for individuals serving on the Board of Directors or as officers of Health Matters Clinic. The policy covers legal defense costs, settlements, and judgments that may arise from claims alleging wrongful acts committed in their capacity as directors or officers.\n\nD&O insurance is a standard and essential protection for nonprofit board members. It ensures that individuals are not personally financially responsible for claims arising from good-faith decisions made in the course of their Board service.' },
      { heading: 'What is Covered', body: 'HMC\'s D&O policy generally covers claims arising from:\n\n\u2022 Breach of fiduciary duty allegations\n\u2022 Mismanagement of organizational funds\n\u2022 Employment practices claims (wrongful termination, discrimination, harassment)\n\u2022 Regulatory investigations and proceedings\n\u2022 Failure to comply with laws or regulations\n\u2022 Errors in judgment or administrative decisions\n\u2022 Claims by third parties alleging harm from Board decisions\n\nCoverage typically includes:\n\u2022 Legal defense costs (attorney fees, court costs, expert witness fees)\n\u2022 Settlements and judgments\n\u2022 Investigation costs\n\u2022 Defense costs for regulatory proceedings' },
      { heading: 'What is NOT Covered', body: 'D&O policies typically exclude:\n\n\u2022 Criminal acts, fraud, or intentional misconduct — Acts committed knowingly and with intent to cause harm\n\u2022 Personal profit or advantage — Claims arising from situations where a director gained personal profit to which they were not entitled\n\u2022 Prior known claims — Claims or circumstances known before the policy inception date\n\u2022 Bodily injury or property damage — These are covered by General Liability insurance, not D&O\n\u2022 Professional medical malpractice — Covered by separate Professional Liability insurance\n\nImportant: D&O insurance protects directors acting in good faith. Directors who engage in fraud, criminal activity, or knowingly violate their fiduciary duties are not protected.' },
      { heading: 'Policy Details', body: 'Note: Specific policy details are maintained by the Executive Director and Finance, Audit & Risk Committee. The following are general parameters:\n\nInsurance Carrier: [To be confirmed by Finance Committee]\nPolicy Period: Annual, renewed each fiscal year\nCoverage Limit: [To be confirmed — typical nonprofit D&O coverage ranges from $1M to $5M]\nDeductible: [To be confirmed]\nPremium: Paid from organizational operating budget; reviewed annually by Finance Committee\n\nFor specific policy details, contact the Executive Director or the Treasurer.' },
      { heading: 'Your Protection as a Board Member', body: 'As a board member of HMC, you are protected by:\n\n1. D&O Insurance — Financial protection against claims arising from Board service\n2. Bylaws Indemnification — HMC\'s Bylaws provide for indemnification of directors to the fullest extent permitted by California law\n3. California Nonprofit Corporation Law — Provides statutory protections for volunteer directors acting in good faith\n4. Business Judgment Rule — Directors are protected from personal liability when making informed, good-faith decisions in the organization\'s best interest\n\nTo maintain your protection:\n\u2022 Always act in good faith and in the best interest of HMC\n\u2022 Attend meetings and review materials — fulfill your Duty of Care\n\u2022 Disclose conflicts of interest promptly — fulfill your Duty of Loyalty\n\u2022 Ensure HMC operates within its mission and the law — fulfill your Duty of Obedience\n\u2022 Complete annual Conflict of Interest Disclosure\n\u2022 Participate in governance training as required' }
    ]
  }
};
